#ifndef DYNAMICSHADER_H
#define DYNAMICSHADER_H

#include "MapData.h"
#include "TileGroup.h"
#include "Vector3.h"

//This class calculates new shading/shadows opacity, etc... This is the dynamic shader.
class DynamicShader
{
    public:
        DynamicShader(MapData &mapData, TileGroup &mapTg, TileGroup &shadowsTg);

        //Calculates generated shadow from a tile coordinates
        void updateShading(const Vector3 coord);

        //To calculates generated shadows from all tiles of the tilegroup
        void updateShadingOfAll();

        //To update the entire shading system by taking in account tiles opacity
        void updateOpacityOfAll();

        //To update the shadows generated by a certain tile type taking in account their opacity
        void updateOpacityOfType(const unsigned int type);

        //To update a shadow opacity taking in account of the tile opacity
        void updateOpacityOfSpecific(const Vector3 type);

        //To get the generated shadow z coordinate, from the 3D tile coord that generates it
        unsigned int getShadowZ(const Vector3 tileCoord);

    private:
        //Reference to MData to get needed informations
        MapData &m_mapData;
        //Reference to the map tilegroup to get tiles opacity values
        TileGroup &m_mapTg;
        //Reference to the shadows tilegroup to operate on it
        TileGroup &m_shadowsTg;
};

#endif // DYNAMICSHADER_H
