#ifndef DYNAMICSHADER_H
#define DYNAMICSHADER_H

#include "MData.h"
#include "TileGroup.h"
#include "../ExternClasses/Vector3.h"

class DynamicShader
{
    public:
        DynamicShader(MData &mapData, TileGroup &mapTg, TileGroup &shadowsTg);

        //Call updating shading by tile coord
        void updateShading(const Vector3 coord);

        //To update the entire shading system by taking in account tile opacity
        void updateOpacityOfAll();
        //To update the shadows generated by a certain tile type taking in account tile opacity
        void updateOpacityOfType(const unsigned int type);
        //To update a shadow opacity taking in account of the tile opacity
        void updateOpacityOfSpecific(const Vector3 type);
        //To get the generated shadow z coordinates, from the tile coord that generates it
        unsigned int getShadowZ(const Vector3 tileCoord);

    private:
        MData &m_mapData;
        TileGroup &m_mapTg;
        TileGroup &m_shadowsTg;
};

#endif // DYNAMICSHADER_H
